# Generated by Django 4.1.3 on 2022-11-13 23:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_followlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='number_of_like',
        ),
        migrations.AddField(
            model_name='post',
            name='fan',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
